name: StandardRB

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  standardrb:
    name: StandardRB Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Read ruby version
      run: echo ::set-output name=RUBY_VERSION::$(([ -f .ruby-version ] && cat .ruby-version) || '3.2.1')
      id: rv
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ steps.rv.outputs.RUBY_VERSION }}"
    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run standardrb
      run: bin/standardrb
